<?php

use Illuminate\Database\Seeder;

class SocietiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('societies')->insert([
            ['city_id'=>1, 'society'=> "DHA Defence"],
            ['city_id'=>1, 'society'=> "Bahria Town"],
            ['city_id'=>1, 'society'=> "Johar Town"],
            ['city_id'=>1, 'society'=> "Allama Iqbal Town"],
            ['city_id'=>1, 'society'=> "Askari"],
            ['city_id'=>1, 'society'=> "Wapda Town"],
            ['city_id'=>1, 'society'=> "Gulberg"],
            ['city_id'=>1, 'society'=> "Eden"],
            ['city_id'=>1, 'society'=> "Cantt"],
            ['city_id'=>1, 'society'=> "Askari"],
            ['city_id'=>1, 'society'=> "Model Town"],
            ['city_id'=>1, 'society'=> "Valencia Housing Society"],
            ['city_id'=>1, 'society'=> "State Life Housing Society"],
            ['city_id'=>1, 'society'=> "Pak Arab Housing Society"],
            ['city_id'=>1, 'society'=> "Sabzazar Scheme"],
            ['city_id'=>1, 'society'=> "Paragon City"],
            ['city_id'=>1, 'society'=> "Faisal Town"],
            ['city_id'=>1, 'society'=> "Military Accounts Housing"],
            ['city_id'=>1, 'society'=> "PIA Housing Scheme"],
            ['city_id'=>1, 'society'=> "Garden Town"],
            ['city_id'=>1, 'society'=> "Punjab Coop Housing Society"],
            ['city_id'=>1, 'society'=> "Samanabad"],
            ['city_id'=>1, 'society'=> "Township"],
            ['city_id'=>1, 'society'=> "EME Society"],
            ['city_id'=>1, 'society'=> "Gulshan-e-Ravi"],
            ['city_id'=>1, 'society'=> "Cavalry Ground"],
            ['city_id'=>1, 'society'=> "Marghzar Officers Colony"],
            ['city_id'=>1, 'society'=> "Bedian Road"],
            ['city_id'=>1, 'society'=> "PCSIR Housing Scheme"],
            ['city_id'=>1, 'society'=> "Divine Gardens"],
            ['city_id'=>1, 'society'=> "Harbanspura"],
            ['city_id'=>1, 'society'=> "Khayaban-e-Amin"],
            ['city_id'=>1, 'society'=> "Tariq Gardens"],
            ['city_id'=>1, 'society'=> "Ferozepur Road"],
            ['city_id'=>1, 'society'=> "Multan Road"],
            ['city_id'=>1, 'society'=> "Bahria Orchard"],
            ['city_id'=>1, 'society'=> "The Spring Apartment Homes"],
            ['city_id'=>1, 'society'=> "Central Park Housing Scheme"],
            ['city_id'=>1, 'society'=> "Walton Road"],
            ['city_id'=>1, 'society'=> "Bahria Nasheman"],
            ['city_id'=>1, 'society'=> "BOR Board of Revenue Housing"],
            ['city_id'=>1, 'society'=> "Sheranwala Heights"],
            ['city_id'=>1, 'society'=> "Ichhra"],
            ['city_id'=>1, 'society'=> "Taj Bagh"],
            ['city_id'=>1, 'society'=> "Punjab Govt Employees Society"],
            ['city_id'=>1, 'society'=> "Architects Engineers Housing"],
            ['city_id'=>1, 'society'=> "Mughalpura"],
            ['city_id'=>1, 'society'=> "Gulshan-e-Lahore"],
            ['city_id'=>1, 'society'=> "NFC 1"],
            ['city_id'=>1, 'society'=> "Lalazar"],
            ['city_id'=>1, 'society'=> "Tajpura"],
            ['city_id'=>1, 'society'=> "Sui Gas Housing Society"],
            ['city_id'=>1, 'society'=> "Lake City"],
            ['city_id'=>1, 'society'=> "Green City"],
            ['city_id'=>1, 'society'=> "Canal Garden"],
            ['city_id'=>1, 'society'=> "Icon Valley"],
            ['city_id'=>1, 'society'=> "Izmir Town"],
            ['city_id'=>1, 'society'=> "Lahore Medical Housing Society"],
            ['city_id'=>1, 'society'=> "Jubilee Town"],
            ['city_id'=>1, 'society'=> "Baghbanpura"],
            ['city_id'=>1, 'society'=> "Sukh Chayn Gardens"],
            ['city_id'=>1, 'society'=> "Shahdara"],
            ['city_id'=>1, 'society'=> "Raiwind Road"],
            ['city_id'=>1, 'society'=> "Main Canal Road"],
            ['city_id'=>1, 'society'=> "College Road"],
            ['city_id'=>1, 'society'=> "Punjab Govt Servant Society"],
            ['city_id'=>1, 'society'=> "Vital Homes Housing Scheme"],
            ['city_id'=>1, 'society'=> "Air Avenue"],
            ['city_id'=>1, 'society'=> "Al-Raheem Garden"],
            ['city_id'=>1, 'society'=> "Garrison Homes"],
            ['city_id'=>1, 'society'=> "Alfalah Town"],
            ['city_id'=>1, 'society'=> "Shadbagh"],
            ['city_id'=>1, 'society'=> "Al Rehman Garden"],
            ['city_id'=>1, 'society'=> "Revenue Society"],
            ['city_id'=>1, 'society'=> "Airline Housing Society"],
            ['city_id'=>1, 'society'=> "Abdalians Housing Society"],
            ['city_id'=>1, 'society'=> "Shah Jamal"],
            ['city_id'=>1, 'society'=> "Muslim Town"],
            ['city_id'=>1, 'society'=> "Garhi Shahu"],
            ['city_id'=>1, 'society'=> "Lahore Motorway City"],
            ['city_id'=>1, 'society'=> "Al Hafeez Gardens"],
            ['city_id'=>1, 'society'=> "Airport Road"],
            ['city_id'=>1, 'society'=> "Clifton Colony"],
            ['city_id'=>1, 'society'=> "Nasheman-e-Iqbal"],
            ['city_id'=>1, 'society'=> "Canal View"],
            ['city_id'=>1, 'society'=> "Nespak Housing Scheme"],
            ['city_id'=>1, 'society'=> "Fateh Garh"],
            ['city_id'=>1, 'society'=> "Iqbal Park"],
            ['city_id'=>1, 'society'=> "Wocland Villas"],
            ['city_id'=>1, 'society'=> "Park View"],
            ['city_id'=>1, 'society'=> "Punjab Small Industries Colony"],
            ['city_id'=>1, 'society'=> "Sanda"],
            ['city_id'=>1, 'society'=> "Awan Town"],
            ['city_id'=>1, 'society'=> "Park View Villas"],
            ['city_id'=>1, 'society'=> "Ghaziabad"],
            ['city_id'=>1, 'society'=> "Immad Garden Housing Scheme"],
            ['city_id'=>1, 'society'=> "Green Town"],
            ['city_id'=>1, 'society'=> "Canal Bank Housing Scheme"],
            ['city_id'=>1, 'society'=> "Islampura"],
            ['city_id'=>1, 'society'=> "Mehar Fayaz Colony"],
            ['city_id'=>1, 'society'=> "PCSIR Staff Colony"],
            ['city_id'=>1, 'society'=> "Nawab Town"],
            ['city_id'=>1, 'society'=> "UET Housing Society"],
            ['city_id'=>1, 'society'=> "New Muslim Town"],
            ['city_id'=>1, 'society'=> "Pace Woodlands"],
            ['city_id'=>1, 'society'=> "HBFC Housing Society"],
            ['city_id'=>1, 'society'=> "Zaheer Villas"],
            ['city_id'=>1, 'society'=> "Eden Avenue Extension"],
            ['city_id'=>1, 'society'=> "Nishtar Colony"],
            ['city_id'=>1, 'society'=> "Dubai Town"],
            ['city_id'=>1, 'society'=> "Shalimar Town"],
            ['city_id'=>1, 'society'=> "Medical Housing Scheme"],
            ['city_id'=>1, 'society'=> "Upper Mall"],
            ['city_id'=>1, 'society'=> "Grand Avenues Housing Scheme"],
            ['city_id'=>1, 'society'=> "Chauburji Park"],
            ['city_id'=>1, 'society'=> "Nishat Colony"],
            ['city_id'=>1, 'society'=> "Elite Town"],
            ['city_id'=>1, 'society'=> "Chungi Amar Sadhu"],
            ['city_id'=>1, 'society'=> "New Super Town"],
            ['city_id'=>1, 'society'=> "Fazaia Housing Scheme"],
            ['city_id'=>1, 'society'=> "Iqbal Avenue"],
            ['city_id'=>1, 'society'=> "Eden Villas"],
            ['city_id'=>1, 'society'=> "Green Park Society"],
            ['city_id'=>1, 'society'=> "Mustafa Town"],
            ['city_id'=>1, 'society'=> "Jail Road"],
            ['city_id'=>1, 'society'=> "Super Town"],
            ['city_id'=>1, 'society'=> "Thokar Niaz Baig"],
            ['city_id'=>1, 'society'=> "Audit & Accounts Housing Society"],
            ['city_id'=>1, 'society'=> "Dream Gardens"],
            ['city_id'=>1, 'society'=> "Bund Road"],
            ['city_id'=>1, 'society'=> "Hajvery Housing Scheme"],
            ['city_id'=>1, 'society'=> "GT Road"],
            ['city_id'=>1, 'society'=> "Shalimar Link Road"],
            ['city_id'=>1, 'society'=> "Guldasht Town"],
            ['city_id'=>1, 'society'=> "Shadman 1"],
            ['city_id'=>1, 'society'=> "Karim Park"],
            ['city_id'=>1, 'society'=> "Harbanspura Road"],
            ['city_id'=>1, 'society'=> "Zaman Colony"],
            ['city_id'=>1, 'society'=> "Bhatta Chowk"],
            ['city_id'=>1, 'society'=> "Nazir Garden Society"],
            ['city_id'=>1, 'society'=> "Dharampura"],
            ['city_id'=>1, 'society'=> "Hassan Town"],
            ['city_id'=>1, 'society'=> "Al Faisal Town"],
            ['city_id'=>1, 'society'=> "AWT Army Welfare Trust"],
            ['city_id'=>1, 'society'=> "Mansoorah"],
            ['city_id'=>1, 'society'=> "Al Rahim Homes"],
            ['city_id'=>1, 'society'=> "Walled City"],
            ['city_id'=>1, 'society'=> "Sunfort Gardens"],
            ['city_id'=>1, 'society'=> "Green Cap Housing Society"],
            ['city_id'=>1, 'society'=> "Formanites Housing Scheme"],
            ['city_id'=>1, 'society'=> "Rehmanpura (Ferozpur Road)"],
            ['city_id'=>1, 'society'=> "Aabpara Coop Housing Society"],
            ['city_id'=>1, 'society'=> "Lahore Cantt Coop Housing"],
            ['city_id'=>1, 'society'=> "Tricon Village"],
            ['city_id'=>1, 'society'=> "Spring Meadows"],
            ['city_id'=>1, 'society'=> "Wahdat Road"],
            ['city_id'=>1, 'society'=> "Ittifaq Town"],
            ['city_id'=>1, 'society'=> "Ittehad Colony"],
            ['city_id'=>1, 'society'=> "Wahdat Colony"],
            ['city_id'=>1, 'society'=> "Lahore Canal Bank Cooperative"],
            ['city_id'=>1, 'society'=> "Cantt View Society"],
            ['city_id'=>1, 'society'=> "Sher Shah Colony"],
            ['city_id'=>1, 'society'=> "Sant Nagar"],
            ['city_id'=>1, 'society'=> "Al Hamad Colony"],
            ['city_id'=>1, 'society'=> "Defence Road"],
            ['city_id'=>1, 'society'=> "Atta Bakhsh Road"],
            ['city_id'=>1, 'society'=> "Salaar Residency"],
            ['city_id'=>1, 'society'=> "TECH Society"],
            ['city_id'=>1, 'society'=> "Ali View Park"],
            ['city_id'=>1, 'society'=> "Green Fort"],
            ['city_id'=>1, 'society'=> "Nayyab Villas"],
            ['city_id'=>1, 'society'=> "Zaman Park"],
            ['city_id'=>1, 'society'=> "PASSCO Housing Society"],
            ['city_id'=>1, 'society'=> "Rail Town (Canal City)"],
            ['city_id'=>1, 'society'=> "Kamahan Road"],
            ['city_id'=>1, 'society'=> "Sheraz Town"],
            ['city_id'=>1, 'society'=> "Lawrence Road"],
            ['city_id'=>1, 'society'=> "Madina Colony"],
            ['city_id'=>1, 'society'=> "Mohafiz Town"],
            ['city_id'=>1, 'society'=> "Jallo"],
            ['city_id'=>1, 'society'=> "PAF Society"],
            ['city_id'=>1, 'society'=> "Bankers Co-operative Housing"],
            ['city_id'=>1, 'society'=> "Peco Road"],
            ['city_id'=>1, 'society'=> "Al Ameen Society"],
            ['city_id'=>1, 'society'=> "Judicial Colony"],
            ['city_id'=>1, 'society'=> "Sunny Park"],
            ['city_id'=>1, 'society'=> "Ali Alam Garden"],
            ['city_id'=>1, 'society'=> "Allama Iqbal Intl Airport"],
            ['city_id'=>1, 'society'=> "Chinar Bagh"],
            ['city_id'=>1, 'society'=> "Royal Residencia"],
            ['city_id'=>1, 'society'=> "Badami Bagh"],
            ['city_id'=>1, 'society'=> "China Scheme"],
            ['city_id'=>1, 'society'=> "Beacon House Society"],
            ['city_id'=>1, 'society'=> "Ravi Road"],
            ['city_id'=>1, 'society'=> "T & T Aabpara Housing Society"],
            ['city_id'=>1, 'society'=> "Kot Lakhpat"],
            ['city_id'=>1, 'society'=> "Daroghewala"],
            ['city_id'=>1, 'society'=> "Rehman Gardens"],
            ['city_id'=>1, 'society'=> "Riwaz Garden"],
            ['city_id'=>1, 'society'=> "Shabbir Town"],
            ['city_id'=>1, 'society'=> "Rehman Villas"],
            ['city_id'=>1, 'society'=> "Mozang"],
            ['city_id'=>1, 'society'=> "Royal Garden"],
            ['city_id'=>1, 'society'=> "Officer Colony"],
            ['city_id'=>1, 'society'=> "DHA 11 Rahbar"],
            ['city_id'=>1, 'society'=> "Altaf Colony"],
            ['city_id'=>1, 'society'=> "Ali View Garden"],
            ['city_id'=>1, 'society'=> "Lahore Press Club Housing Scheme"],
            ['city_id'=>1, 'society'=> "Naz Town"],
            ['city_id'=>1, 'society'=> "Heaven Homes"],
            ['city_id'=>1, 'society'=> "Misri Shah"],
            ['city_id'=>1, 'society'=> "Raj Garh"],
            ['city_id'=>1, 'society'=> "Shalimar Housing Scheme"],
            ['city_id'=>1, 'society'=> "P & D Housing Society"],
            ['city_id'=>1, 'society'=> "Mateen Avenue"],
            ['city_id'=>1, 'society'=> "IEP Engineers Town"],
            ['city_id'=>1, 'society'=> "Cricketer Villas"],
            ['city_id'=>1, 'society'=> "Davis Road"],
            ['city_id'=>1, 'society'=> "Al Noor Town"],
            ['city_id'=>1, 'society'=> "Rehman Park"],
            ['city_id'=>1, 'society'=> "Green Acres Housing Society"],
            ['city_id'=>1, 'society'=> "Beadon Road"],
            ['city_id'=>1, 'society'=> "Rajpoot Town"],
            ['city_id'=>1, 'society'=> "Bilal Gunj"],
            ['city_id'=>1, 'society'=> "Army Housing Society"],
            ['city_id'=>1, 'society'=> "Muslim Nagar Housing Scheme"],
            ['city_id'=>1, 'society'=> "Lower Mall"],
            ['city_id'=>1, 'society'=> "Batapur"],
            ['city_id'=>1, 'society'=> "New Chauburji Park"],
            ['city_id'=>1, 'society'=> "Saadi Park"],
            ['city_id'=>1, 'society'=> "Rustam Park"],
            ['city_id'=>1, 'society'=> "Al Jalil Garden"],
            ['city_id'=>1, 'society'=> "Azam Gardens"],
            ['city_id'=>1, 'society'=> "Meharpura"],
            ['city_id'=>1, 'society'=> "Ali Town"],
            ['city_id'=>1, 'society'=> "Government Employees"],
            ['city_id'=>1, 'society'=> "Gulbahar Colony"],
            ['city_id'=>1, 'society'=> "Sherwanee Town Housing Scheme"],
            ['city_id'=>1, 'society'=> "Jora Pull"],
            ['city_id'=>1, 'society'=> "Anarkali"],
            ['city_id'=>1, 'society'=> "LDA Avenue"],
            ['city_id'=>1, 'society'=> "Khayaban-e-Zohra"],
            ['city_id'=>1, 'society'=> "Lalazaar Garden"],
            ['city_id'=>1, 'society'=> "Eden Place Housing Scheme"],
            ['city_id'=>1, 'society'=> "Kahna"],
            ['city_id'=>1, 'society'=> "Gujjarpura"],
            ['city_id'=>1, 'society'=> "Islamia Park"],
            ['city_id'=>1, 'society'=> "Fort Villas"],
            ['city_id'=>1, 'society'=> "Bismillah Housing Scheme"],
            ['city_id'=>1, 'society'=> "Rana Town"],
            ['city_id'=>1, 'society'=> "Ring Road"],
            ['city_id'=>1, 'society'=> "Mehmood Booti"],
            ['city_id'=>1, 'society'=> "Nizamabad"],
            ['city_id'=>1, 'society'=> "Mominpur"],
            ['city_id'=>1, 'society'=> "Nisbat Road"],
            ['city_id'=>1, 'society'=> "Dilkusha Gardens"],
            ['city_id'=>1, 'society'=> "Shadman "],
            ['city_id'=>1, 'society'=> "Aitchison Society"],
            ['city_id'=>1, 'society'=> "Babar Homes"],
            ['city_id'=>1, 'society'=> "Ravi Park"],
            ['city_id'=>1, 'society'=> "Ghous Garden"],
            ['city_id'=>1, 'society'=> "Gul-e-Damin"],
            ['city_id'=>1, 'society'=> "NFC 2"],
            ['city_id'=>1, 'society'=> "Aashiana Road"],
            ['city_id'=>1, 'society'=> "Sahafi Colony"],
            ['city_id'=>1, 'society'=> "Wafaqi Colony"],
            ['city_id'=>1, 'society'=> "Mian Amiruddin Park"],
            ['city_id'=>1, 'society'=> "West Wood Housing Society"],
            ['city_id'=>1, 'society'=> "Gulshan Colony"],
            ['city_id'=>1, 'society'=> "Jamil Town"],
            ['city_id'=>1, 'society'=> "Farooq Colony"],
            ['city_id'=>1, 'society'=> "Rizwan Garden Scheme"],
            ['city_id'=>1, 'society'=> "Defence Fort"],
            ['city_id'=>1, 'society'=> "Saqib Town"],
            ['city_id'=>1, 'society'=> "Iqbal Colony"],
            ['city_id'=>1, 'society'=> "GOR"],
            ['city_id'=>1, 'society'=> "Krishan Nagar"],
            ['city_id'=>1, 'society'=> "Singhpura"],
            ['city_id'=>1, 'society'=> "Canal Burg"],
            ['city_id'=>1, 'society'=> "Toheed Park"],
            ['city_id'=>1, 'society'=> "Shah Kamal"],
            ['city_id'=>1, 'society'=> "Sundar Estate"],
            ['city_id'=>1, 'society'=> "Ameer-ud-Din Park"],
            ['city_id'=>1, 'society'=> "Empress Road"],
            ['city_id'=>1, 'society'=> "Kacha Jail Road"],
            ['city_id'=>1, 'society'=> "Wassanpura"],
            ['city_id'=>1, 'society'=> "OPF Housing Scheme"],
            ['city_id'=>1, 'society'=> "Al-Hafiz Town"],
            ['city_id'=>1, 'society'=> "Real Cottages"],
            ['city_id'=>1, 'society'=> "DHA City"],
            ['city_id'=>1, 'society'=> "Gulshan-e-Ahbab"],
            ['city_id'=>1, 'society'=> "Kot Khawaja Saeed"],
            ['city_id'=>1, 'society'=> "Mohlanwal Scheme"],
            ['city_id'=>1, 'society'=> "Rehman Housing Society"],
            ['city_id'=>1, 'society'=> "Shoukat Town"],
            ['city_id'=>1, 'society'=> "Gawalmandi"],
            ['city_id'=>1, 'society'=> "Al Hamra Town"],
            ['city_id'=>1, 'society'=> "Gosha-e-Ahbab"],
            ['city_id'=>1, 'society'=> "Madina Homes"],
            ['city_id'=>1, 'society'=> "Venus Housing Scheme"],
            ['city_id'=>1, 'society'=> "Al Madina Avenue"],
            ['city_id'=>1, 'society'=> "Malik Park"],
            ['city_id'=>1, 'society'=> "Peer Colony"],
            ['city_id'=>1, 'society'=> "Youhanabad"],
            ['city_id'=>1, 'society'=> "Shadab Garden"],
            ['city_id'=>1, 'society'=> "Shershah Colony"],
            ['city_id'=>1, 'society'=> "Kahna Kacha"],
            ['city_id'=>1, 'society'=> "Salli Town"],
            ['city_id'=>1, 'society'=> "Abid Market"],
            ['city_id'=>1, 'society'=> "Brandreth Road"],
            ['city_id'=>1, 'society'=> "Manga - Raiwind Road"],
            ['city_id'=>1, 'society'=> "Bahria Education & Medical City"],
            ['city_id'=>1, 'society'=> "Dogech"],
            ['city_id'=>1, 'society'=> "Maulana Shaukat Ali Road"],
            ['city_id'=>1, 'society'=> "Excise & Taxation Housing Scheme"],
            ['city_id'=>1, 'society'=> "Hall Road"],
            ['city_id'=>1, 'society'=> "Highcourt Society"],
            ['city_id'=>1, 'society'=> "Salamatpura"],
            ['city_id'=>1, 'society'=> "Sufiabad"],
            ['city_id'=>1, 'society'=> "Haji Park Housing Scheme"],
            ['city_id'=>1, 'society'=> "Al Jannat Housing Scheme"],
            ['city_id'=>1, 'society'=> "Sham Nagar"],
            ['city_id'=>1, 'society'=> "Gulzar Colony"],
            ['city_id'=>1, 'society'=> "United Bank Officers"],
            ['city_id'=>1, 'society'=> "Jalal Colony"],
            ['city_id'=>1, 'society'=> "Sadaat Town"],
            ['city_id'=>1, 'society'=> "Manawan"],
            ['city_id'=>1, 'society'=> "Jaffaria Colony"],
            ['city_id'=>1, 'society'=> "Lytton Road"],
            ['city_id'=>1, 'society'=> "Bahar Colony"],
            ['city_id'=>1, 'society'=> "Lakhodher"],
            ['city_id'=>1, 'society'=> "Gulfishan Town"],
            ['city_id'=>1, 'society'=> "Gulshan-E-Mustafa Housing"],
            ['city_id'=>1, 'society'=> "Irum Garden Housing Society"],
            ['city_id'=>1, 'society'=> "Kotli Abdur Rahman"],
            ['city_id'=>1, 'society'=> "Angoori Bagh"],
            ['city_id'=>1, 'society'=> "Agrics Town"],
            ['city_id'=>1, 'society'=> "Siddiqia Colony"],
            ['city_id'=>1, 'society'=> "Mason Road"],
            ['city_id'=>1, 'society'=> "Karbath"],
            ['city_id'=>1, 'society'=> "Ameen Park"],
            ['city_id'=>1, 'society'=> "Waris Road"],
            ['city_id'=>1, 'society'=> "Saidpur"],
            ['city_id'=>1, 'society'=> "Saroba Gardens Housing Society"],
            ['city_id'=>1, 'society'=> "Chaman Park"],
            ['city_id'=>1, 'society'=> "Jaffar Town"],
            ['city_id'=>1, 'society'=> "Abbot Road"],
            ['city_id'=>1, 'society'=> "Lahore Avenue"],
            ['city_id'=>1, 'society'=> "Doctors Housing Society"],
            ['city_id'=>1, 'society'=> "Eden Park"],
            ['city_id'=>1, 'society'=> "Alpha Society"],
            ['city_id'=>1, 'society'=> "Waris Colony"],
            ['city_id'=>1, 'society'=> "Rang Mahal"],
            ['city_id'=>1, 'society'=> "Khokhar Town"],
            ['city_id'=>1, 'society'=> "Gulistan Colony"],
            ['city_id'=>1, 'society'=> "Rehmat Colony"],
            ['city_id'=>1, 'society'=> "McLeod Road"],
            ['city_id'=>1, 'society'=> "Waheed Brother Colony"],
            ['city_id'=>1, 'society'=> "Shiraz Villas"],
            ['city_id'=>1, 'society'=> "Mian Aziz Garden"],
            ['city_id'=>1, 'society'=> "National Town"],
            ['city_id'=>1, 'society'=> "Mushtaq Park - Phase 3"],
            ['city_id'=>1, 'society'=> "Ashiana-e-Quaid Housing Scheme"],
            ['city_id'=>1, 'society'=> "Lakshmi Chowk"],
            ['city_id'=>1, 'society'=> "Al Kareem Garden"],
            ['city_id'=>1, 'society'=> "Canal Fort II"],
            ['city_id'=>1, 'society'=> "Jewa Town"],
            ['city_id'=>1, 'society'=> "LDA City"],
            ['city_id'=>1, 'society'=> "Gujjar Colony"],
            ['city_id'=>1, 'society'=> "Expo Avenue Society"],
            ['city_id'=>1, 'society'=> "Qadri Colony"],
            ['city_id'=>1, 'society'=> "Railway Officers Colony"],
            ['city_id'=>1, 'society'=> "Saggian"],
            ['city_id'=>1, 'society'=> "Umer Colony"],
            ['city_id'=>1, 'society'=> "Yasrab Colony"],
            ['city_id'=>1, 'society'=> "Al Raheem Town"],
            ['city_id'=>1, 'society'=> "Rasool Park"],
            ['city_id'=>1, 'society'=> "Begampura"],
            ['city_id'=>1, 'society'=> "Sue-e-Asal"],
            ['city_id'=>1, 'society'=> "Qilla Gujjar Singh"],
            ['city_id'=>1, 'society'=> "Chaudhary Colony"],
            ['city_id'=>1, 'society'=> "Prime Homes 1"],
            ['city_id'=>1, 'society'=> "Dream Avenue Lahore"],
            ['city_id'=>1, 'society'=> "Urdu Bazar"],
            ['city_id'=>1, 'society'=> "Mian Mir Colony"],
            ['city_id'=>1, 'society'=> "Manga Mandi"],
            ['city_id'=>1, 'society'=> "Makkah Colony"],
            ['city_id'=>1, 'society'=> "Mall Road"],
            ['city_id'=>1, 'society'=> "Allama Iqbal Road"],
            ['city_id'=>1, 'society'=> "Gajju Matah"],
            ['city_id'=>1, 'society'=> "IBL Housing Scheme"],
            ['city_id'=>1, 'society'=> "Gulshan Farooq Colony"],
            ['city_id'=>1, 'society'=> "Ahmad Avenue"],
            ['city_id'=>1, 'society'=> "Hamza Town"],
            ['city_id'=>1, 'society'=> "Bahawalpur Road"],
            ['city_id'=>1, 'society'=> "Pine Villas"],
            ['city_id'=>1, 'society'=> "Ghausia Colony"],
            ['city_id'=>1, 'society'=> "Walton Railway Officers Colony"],
            ['city_id'=>1, 'society'=> "Poonch Road"],
            ['city_id'=>1, 'society'=> "Aibak Road"],
            ['city_id'=>1, 'society'=> "Government Transport"],
            ['city_id'=>1, 'society'=> "Nadeem Shaheed Road"],
            ['city_id'=>1, 'society'=> "Govt Officers Housing Society"],
            ['city_id'=>1, 'society'=> "Sultan Pura"],
            ['city_id'=>1, 'society'=> "Chah Miran"],
            ['city_id'=>1, 'society'=> "Crescent Town"],
            ['city_id'=>1, 'society'=> "Canal Colony"],
            ['city_id'=>1, 'society'=> "Birdwood Road"],
            ['city_id'=>1, 'society'=> "Temple Road"]
        ]);
    }
}
